name: 🎉 Release Binary
on:
  create:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.4
      - name: Install Dependences
        run: |
          brew install libpcap
#          git submodule update --init --recursive --remote
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release -f .github/build/mac.yml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # https://github.com/marketplace/actions/run-on-architecture#supported-platforms
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.4
      - name: Install Dependences
        run: |
          sudo apt-get update
          sudo apt-get install -yy libgtk-3-dev libwebkit2gtk-4.0-dev
#          https://github.com/webview/webview
#          git submodule update --init --recursive --remote
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release -f .github/build/linux.yml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.4
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release -f .github/build/windows.yml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
